/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiProductsSlugRouteImport } from './routes/api/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSlugRoute = ApiProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/api/products/$slug': typeof ApiProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/api/products/$slug': typeof ApiProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/api/products/$slug': typeof ApiProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/products' | '/products/$slug' | '/api/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/products' | '/products/$slug' | '/api/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/products'
    | '/products/$slug'
    | '/api/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$slug': {
      id: '/api/products/$slug'
      path: '/$slug'
      fullPath: '/api/products/$slug'
      preLoaderRoute: typeof ApiProductsSlugRouteImport
      parentRoute: typeof ApiProductsRoute
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsSlugRoute: typeof ApiProductsSlugRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsSlugRoute: ApiProductsSlugRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
